layout_spectrum: 0.5453244592063129
typography_spectrum: 0.12854943750426173
color:
  brandStrength: 0.7269403806421906
  lightness: 0.5600236884783953
  saturation: 0.2310932306572795
  rhythmicContrast: 0.5102749350480735
  brandColors:
    - '#151314'
    - '#54404B'
    - '#756251'
    - '#F6EFE5'
    - '#E9A370'
content_rating:
  adult: true
author:
  email: PAPERFACE908@gmail.com
name: PAPERFACE
navigation:
  - name: ART
    url: 'https://www.instagram.com/pape908/'
    type: external
  - name: MUSIC
    url: 'https://soundcloud.com/paperface'
    type: external
  - name: VIDEO
    url: 'https://vimeo.com/pape908'
    type: external
  - name: INSTA
    url: 'https://www.instagram.com/paperface908'
    type: external
  - name: TUMBLR
    url: 'http://paperface908.tumblr.com'
    type: external
title: THE MAN
description: Behind the Mask
