typography_spectrum: 0.25398872629739344
content_rating:
  adult: true
color:
  brandStrength: 0.38685234310105443
  lightness: 0.8098700726404786
  saturation: 0.8863587866071612
  rhythmicContrast: 0.15908687585033476
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.2965128510259092
author:
  email: PAPERFACE908@gmail.com
name: PAPERFACE
navigation:
  - name: ART
    url: 'https://www.instagram.com/pape908/'
    type: external
  - name: MUSIC
    url: 'https://soundcloud.com/paperface'
    type: external
  - name: VIDEO
    url: 'https://vimeo.com/pape908'
    type: external
  - name: INSTA
    url: 'https://www.instagram.com/paperface908'
    type: external
  - name: TUMBLR
    url: 'http://paperface908.tumblr.com'
    type: external
title: THE MAN
description: Behind the Mask
