typography_spectrum: 0.25398872629739344
color:
  brandStrength: 0.38685234310105443
  lightness: 0.8098700726404786
  saturation: 0.8863587866071612
  rhythmicContrast: 0.15908687585033476
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.2965128510259092
name: PAPERFACE
title: THE MAN
description: Behind the Mask
